
name: Terraform Test

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  run-script:
    runs-on: ubuntu-latest
    permissions:
        id-token: write
        contents: read

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
          persist-credentials: false
          fetch-depth: 0

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubActions
        aws-region: eu-north-1

    - name: Fetch the caller identity
      run: |
        aws sts get-caller-identity

    - name: Run terraform test script
      run: |
        chmod +x ./bash-test.sh
        ./bash-test.sh
